### ISSUE TITLE
Service returned with error: (unknown) 400 Bad Request - clusters.cluster.x-k8s.io "cluster-example"

### ISSUE THREAD

**Issue by nataliagranato** [MagaluCloud/terraform-provider-mgc#11]
Ao tentar criar o cluster Kubernetes, parece que cria a API, mas os nodegroups falham na criacao. 
```time_sleep.wait_15_minutes: Creation complete after 15m0s [id=2024-06-17T18:17:22Z]
mgc_kubernetes_nodepool.gp1_small: Creating...
╷
│ Error: Unable to create mgc_kubernetes_nodepool
│ 
│   with mgc_kubernetes_nodepool.gp1_small,
│   on main.tf line 28, in resource "mgc_kubernetes_nodepool" "gp1_small":
│   28: resource "mgc_kubernetes_nodepool" "gp1_small" {
│ 
│ Service returned with error: (unknown) 400 Bad Request - cluster in provisioning (request-id:
│ e72576d9-c9d4-42d3-aedc-29530a243ecb)
╵
╷
│ Error: Unable to create mgc_kubernetes_cluster
│ 
│   with mgc_kubernetes_cluster.cluster_with_nodepool,
│   on main.tf line 42, in resource "mgc_kubernetes_cluster" "cluster_with_nodepool":
│   42: resource "mgc_kubernetes_cluster" "cluster_with_nodepool" {
│ 
│ Service returned with error: (unknown) 400 Bad Request - clusters.cluster.x-k8s.io "cluster-example"
│ already exists (request-id: 339f6110-7b9b-4db9-b592-72f594e4432d)
time_sleep.wait_15_minutes: Creation complete after 15m0s [id=2024-06-17T18:17:22Z]
mgc_kubernetes_nodepool.gp1_small: Creating...
╷
│ Error: Unable to create mgc_kubernetes_nodepool
│ 
│   with mgc_kubernetes_nodepool.gp1_small,
│   on main.tf line 28, in resource "mgc_kubernetes_nodepool" "gp1_small":
│   28: resource "mgc_kubernetes_nodepool" "gp1_small" {
│ 
│ Service returned with error: (unknown) 400 Bad Request - cluster in provisioning (request-id:
│ e72576d9-c9d4-42d3-aedc-29530a243ecb)
╵
╷
│ Error: Unable to create mgc_kubernetes_cluster
│ 
│   with mgc_kubernetes_cluster.cluster_with_nodepool,
│   on main.tf line 42, in resource "mgc_kubernetes_cluster" "cluster_with_nodepool":
│   42: resource "mgc_kubernetes_cluster" "cluster_with_nodepool" {
│ 
│ Service returned with error: (unknown) 400 Bad Request - clusters.cluster.x-k8s.io "cluster-example"
│ already exists (request-id: 339f6110-7b9b-4db9-b592-72f594e4432d)

**Comment by lfpicoloto1** [comment]
Oi
Consegue testar novamente usando a versao mais recente #27 
Se puder compartilhar o arquivo tbem.
Fizemos testes aqui com o exemplo e está funcionando.

**Comment by nataliagranato** [comment]
@lfpicoloto1 Excelente, o problema foi resolvido. Agradeço a gentileza e atenção para melhorarmos. Gostaria de dar uma sugestão, ter um arquivo de provider.tf no repositório de https://github.com/MagaluCloud/terraform-examples com a versão do provider e se possível um passo onde possamos obter o kubeconfig via terraform.
![image](https://github.com/user-attachments/assets/c618aa11-ad74-492e-b355-953abe3fc5d1)

**Comment by nataliagranato** [comment]
> @lfpicoloto1 Excelente, o problema foi resolvido. Agradeço a gentileza e atenção para melhorarmos. Gostaria de dar uma sugestão, ter um arquivo de provider.tf no repositório de https://github.com/MagaluCloud/terraform-examples com a versão do provider e se possível um passo onde possamos obter o kubeconfig via terraform. ![image](https://private-user-images.githubusercontent.com/91998391/350155617-c618aa11-ad74-492e-b355-953abe3fc5d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzkzMDQsIm5iZiI6MTcyMTMzOTAwNCwicGF0aCI6Ii85MTk5ODM5MS8zNTAxNTU2MTctYzYxOGFhMTEtYWQ3NC00OTJlLWIzNTUtOTUzYWJlM2ZjNWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIxNDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OGNhOTc3MmQzZDJkOGZjMTA1ODIxM2MyYjViZDNkNjhhYjcwMDAwOTc0OGVkMWY1OWQ4YWUxN2YxNjkyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lq3x1D7nSKi5tdIL01zIBkmTekcJwbK9YpUVDUl06-I)

Outro detalhe  importante seria termos a opção de guardarmos  o estado do terraform em um bucket da própria Magalu.

**Comment by publi0** [comment]
> @lfpicoloto1 Excelente, o problema foi resolvido. Agradeço a gentileza e atenção para melhorarmos. Gostaria de dar uma sugestão, ter um arquivo de provider.tf no repositório de https://github.com/MagaluCloud/terraform-examples com a versão do provider e se possível um passo onde possamos obter o kubeconfig via terraform. ![image](https://private-user-images.githubusercontent.com/91998391/350155617-c618aa11-ad74-492e-b355-953abe3fc5d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDM4NjYsIm5iZiI6MTcyMTM0MzU2NiwicGF0aCI6Ii85MTk5ODM5MS8zNTAxNTU2MTctYzYxOGFhMTEtYWQ3NC00OTJlLWIzNTUtOTUzYWJlM2ZjNWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIyNTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYTQ2OTMxYTEyZDhiOWMzNTRiNzcyZWY2YzAxNWJkY2M3NWM0ZmY4N2YxOTJmZjZkNTJmNzI5OGY1YmU4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0xr0GIbJiORiWOsRhBUP8jRlV_ECFzzUhiTCgRsbwxo)

Já estamos trabalhando para ter o datasource com o kubconfig disponivel :)



> > @lfpicoloto1 Excelente, o problema foi resolvido. Agradeço a gentileza e atenção para melhorarmos. Gostaria de dar uma sugestão, ter um arquivo de provider.tf no repositório de https://github.com/MagaluCloud/terraform-examples com a versão do provider e se possível um passo onde possamos obter o kubeconfig via terraform. ![image](https://private-user-images.githubusercontent.com/91998391/350155617-c618aa11-ad74-492e-b355-953abe3fc5d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzkzMDQsIm5iZiI6MTcyMTMzOTAwNCwicGF0aCI6Ii85MTk5ODM5MS8zNTAxNTU2MTctYzYxOGFhMTEtYWQ3NC00OTJlLWIzNTUtOTUzYWJlM2ZjNWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIxNDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OGNhOTc3MmQzZDJkOGZjMTA1ODIxM2MyYjViZDNkNjhhYjcwMDAwOTc0OGVkMWY1OWQ4YWUxN2YxNjkyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lq3x1D7nSKi5tdIL01zIBkmTekcJwbK9YpUVDUl06-I)
> 
> Outro detalhe importante seria termos a opção de guardarmos o estado do terraform em um bucket da própria Magalu.

Já é possível! Temos um exemplo aqui: [terraform exemples](https://github.com/MagaluCloud/terraform-examples/tree/main/simple/tf-state-s3-save)
