### ISSUE TITLE
nodepools could not be empty

### ISSUE THREAD

**Issue by lfpicoloto1** [MagaluCloud/terraform-provider-mgc#16]
Estou seguindo o exemplo para criação de kubernetes publicado em nosso Github https://github.com/MagaluCloud/terraform-examples/blob/main/simple/kubernetes/main.tf

Tentei criar um cluster sem nodepools e recebi o erro

![image](https://github.com/MagaluCloud/terraform-provider-mgc/assets/133693873/023fb54f-a826-4a05-8f8b-dd92f483fa34)

**Comment by antonionovaesjr** [comment]
Me too

**Comment by antonionovaesjr** [comment]
Problema continua na versão 0.20.1

```
module.kubernetes_example.mgc_kubernetes_cluster.this[0]: Creating...
╷
│ Error: Unable to create mgc_kubernetes_cluster
│ 
│   with module.kubernetes_example.mgc_kubernetes_cluster.this[0],
│   on ../main.tf line 2, in resource "mgc_kubernetes_cluster" "this":
│    2: resource "mgc_kubernetes_cluster" "this" {
│ 
│ Service returned with error: (unknown) 400 Bad Request - nodepools could not be empty (request-id: abb49933-b3b5-46d7-afa8-8daeaebd651a)
╵
antonio@makr42:~/Projetos/magalu-cloud/terraform-mgc-kubernetes/example> 
```

**Comment by antonionovaesjr** [comment]
Acontece na versão 0.18.10, 0.19.3 e 0.20.1

**Comment by lfpicoloto1** [comment]
Corrigido o exemplo no [repo de exemplos ](https://github.com/MagaluCloud/terraform-examples/tree/main/simple)

Por enquanto ainda não é possível criar o cluster sozinho. É requerido ao menos um nodepool.

Att.
Lucas Picoloto
Product Managar | Magalu Cloud
