### ISSUE TITLE
Cluster kubernetes são criados com falha via terraform

### ISSUE THREAD

**Issue by antonionovaesjr** [MagaluCloud/terraform-provider-mgc#25]
Ao criar cluster usando o provider terraform (versão 0.20.1) e enabled_server_group  como true e enabled_bastion como false, os cluster são criados com erro, mas quando os atributos enabled_server_group  e enabled_bastion são definidos como false, o cluster é criado.

Ao criar com mgc (versão 0.20.0) via linha de comando e via console web o cluster é criado com sucesso.

**Comando usado via mgc cli:**

mgc kubernetes cluster create --description="This is an example cluster." --name="cluster-example" --node-pools='[{"flavor":"cloud-k8s.gp1.small","name":"nodepool-example","replicas":1}]' –param.version="v1.28.5"

**Fonte:** https://docs.magalu.cloud/docs/kubernetes/how-to/clusters/create-cluster

Ao criar node pool usando o recurso mgc_kubernetes_nodepool e passando tags e taint, o node pool não é finalizado ficando eternamente com status “criando”

**Comment by publi0** [comment]
@antonionovaesjr Não estamos conseguindo reproduzir esse erro, você poderia tentar novamente e dizer se ainda acontecendo?
