### ISSUE TITLE
Erro ao criar mgc_network_rules

### ISSUE THREAD

**Issue by danilodorgam** [MagaluCloud/terraform-provider-mgc#3]
ao tentar criar um mgc_network_rules estou recebendo erro que o ethertype é obrigaatorio.
mesmo a documentação falando que é opcional, e mesmo informado o erro permance.
segue arquivo que executei
https://gist.github.com/danilodorgam/76e5f85b022dc58726fd923eb027727b

**Comment by lfpicoloto1** [comment]
Olá @danilodorgam, não consegui abrir o seu gist. Conseguiria compartilhar o seu código do terraform?

**Comment by danilodorgam** [comment]
Vou republicar ele, mas meu erro era que eu estava passsando IPV4 em vez de IPv4 no campo ethertype, porém existe um erro ao meu ver. ele fala que é opcional porém é um campo obrigatorio.
https://registry.terraform.io/providers/MagaluCloud/mgc/latest/docs/resources/network_rules#ethertype

**Comment by lfpicoloto1** [comment]
Realmente, vou adicionar aqui para corrigirmos na doc.

**Comment by antonionovaesjr** [comment]
Vamos trocar experiências https://t.me/openmagalucloud

**Comment by lfpicoloto1** [comment]
Resolvido na versão #56
