### ISSUE TITLE
Documentação Obejct storage

### ISSUE THREAD

**Issue by antonionovaesjr** [MagaluCloud/terraform-provider-mgc#4]
Apesar de possuir o resource mgc_object-storage_buckets não possui documentação sobre o uso dos parâmetros obrigatórios, opcional e etc

https://registry.terraform.io/providers/MagaluCloud/mgc/latest/docs
https://github.com/MagaluCloud/terraform-provider-mgc/tree/v0.18.10/docs/resources

**Comment by lfpicoloto1** [comment]
Criamos a Doc, será adicionada na próxima versão!

Obrigado!
