### ISSUE TITLE
[FEAT] - user_data for mgc_virtual_machine_instances resources

### ISSUE THREAD

**Issue by lnutimura** [MagaluCloud/terraform-provider-mgc#41]
**Is your feature request related to a problem? Please describe.**
No, but it's definitely a _nice-to-have_, given that other cloud providers offer this feature.

**Describe the solution you'd like**
It would be nice if the `mgc` provider had a field analogous to the `--user-data` option in [mgccli](https://github.com/MagaluCloud/mgccli/blob/main/docs/virtual-machine/instances/create/Create%20a%20Virtual%20Machine%20instance.md).

**Describe alternatives you've considered**
I considered using Terraform's built-in [provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax#how-to-use-provisioners) to run scripts remotely in an asynchronous manner, but I ended up not succeeding, i.e., either the script would not run, or it would block the terminal and consequently delay the deployment of each instance.

**Additional context**
N/A.

**Comment by publi0** [comment]
Solved on the latest release v0.29.2
