### ISSUE TITLE
Falha ao criar DBaaS via terraform provider mgc

### ISSUE THREAD

**Issue by antonionovaesjr** [MagaluCloud/terraform-provider-mgc#5]
Falha ao criar DBaaS via terraform provider mgc

╷
│ Error: Unable to create mgc_dbaas_instances
│
│ with module.dbaas-example.mgc_dbaas_instances.this[0],
│ on ../main.tf line 5, in resource "mgc_dbaas_instances" "this":
│ 5: resource "mgc_dbaas_instances" "this" {
│
│ Service returned with error: (BAD_REQUEST) 400 Bad Request - Request validation error (request-id: c45e9f95-016a-4fa1-b4e7-13c7e8cd065e)
![Screenshot_20240609_115211](https://github.com/MagaluCloud/terraform-provider-mgc/assets/7480861/d96c89bb-4b85-40be-a2e0-00107c16142c)

**Comment by lfpicoloto1** [comment]
Olá Antonio, consegue compartilhar o seu código do terraform:

**Comment by antonionovaesjr** [comment]
Olá @lfpicoloto1, o  problema foi o flavor_id, estava passando o nome do flavor, ao passar o ID funcionou corretamente

Grato
