### ISSUE TITLE
[BUG] - Securit group resource v0.27.1

### ISSUE THREAD

**Issue by antonionovaesjr** [MagaluCloud/terraform-provider-mgc#58]
**Describe the bug**
O resource security group não suporta recurso mesmo enstando na documentação, aparenta ter sido substituido por um recurso aparentemente estranho

**To Reproduce**
1. Tentar criar um security group usando esse resource: https://registry.terraform.io/providers/MagaluCloud/mgc/0.27.1/docs/resources/network_security_groups

**Expected behavior**
│   on ../main.tf line 1, in resource "mgc_network_security_groups" "this":
│    1: resource "mgc_network_security_groups" "this" {
│ 
│ The provider magalucloud/mgc does not support resource type "mgc_network_security_groups".

**Desktop (please complete the following information):**
 - OS: Opensuse Leap
 - Version: 15.5 

**Additional context**
o recurso acima aparece ter sido substituido por **mgc_network_security_group_security_groups**

**Comment by publi0** [comment]
Solved on the latest release v0.29.2
